package it.unirc.pwm.ht;
// Generated 12 dic 2023, 12:22:05 by Hibernate Tools 6.1.3.Final

/**
 * Admin generated by hbm2java
 */
public class Admin implements java.io.Serializable {

	private int nomeAdmin;
	private String password;

	public Admin() {
	}

	public Admin(int nomeAdmin) {
		this.nomeAdmin = nomeAdmin;
	}

	public Admin(int nomeAdmin, String password) {
		this.nomeAdmin = nomeAdmin;
		this.password = password;
	}

	public int getNomeAdmin() {
		return this.nomeAdmin;
	}

	public void setNomeAdmin(int nomeAdmin) {
		this.nomeAdmin = nomeAdmin;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
