package it.unirc.pwm.ht;
// Generated 11 dic 2023, 17:22:19 by Hibernate Tools 6.1.3.Final



/**
 * Admin generated by hbm2java
 */
public class Admin  implements java.io.Serializable {


     private String nomeAdmin;
     private String password;

    public Admin() {
    }

    public Admin(String nomeAdmin, String password) {
       this.nomeAdmin = nomeAdmin;
       this.password = password;
    }
   
    public String getNomeAdmin() {
        return this.nomeAdmin;
    }
    
    public void setNomeAdmin(String nomeAdmin) {
        this.nomeAdmin = nomeAdmin;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


