package it.unirc.pwm.ht;
// Generated 11 dic 2023, 17:22:19 by Hibernate Tools 6.1.3.Final


import java.sql.Date;

/**
 * Clienteprime generated by hbm2java
 */
public class Clienteprime  implements java.io.Serializable {


     private int idCliente;
     private Cliente cliente;
     private Date dataInizioIscrizione;
     private Date dataFineIscrizione;
     private byte mensile;

    public Clienteprime() {
    }

    public Clienteprime(Cliente cliente, Date dataInizioIscrizione, Date dataFineIscrizione, byte mensile) {
       this.cliente = cliente;
       this.dataInizioIscrizione = dataInizioIscrizione;
       this.dataFineIscrizione = dataFineIscrizione;
       this.mensile = mensile;
    }
   
    public int getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(int idCliente) {
        this.idCliente = idCliente;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Date getDataInizioIscrizione() {
        return this.dataInizioIscrizione;
    }
    
    public void setDataInizioIscrizione(Date dataInizioIscrizione) {
        this.dataInizioIscrizione = dataInizioIscrizione;
    }
    public Date getDataFineIscrizione() {
        return this.dataFineIscrizione;
    }
    
    public void setDataFineIscrizione(Date dataFineIscrizione) {
        this.dataFineIscrizione = dataFineIscrizione;
    }
    public byte getMensile() {
        return this.mensile;
    }
    
    public void setMensile(byte mensile) {
        this.mensile = mensile;
    }




}


