package it.unirc.pwm.ht;
// Generated 12 dic 2023, 12:22:05 by Hibernate Tools 6.1.3.Final

/**
 * ComponeId generated by hbm2java
 */
public class ComponeId implements java.io.Serializable {

	private int idArticolo;
	private int idCarrello;

	public ComponeId() {
	}

	public ComponeId(int idArticolo, int idCarrello) {
		this.idArticolo = idArticolo;
		this.idCarrello = idCarrello;
	}

	public int getIdArticolo() {
		return this.idArticolo;
	}

	public void setIdArticolo(int idArticolo) {
		this.idArticolo = idArticolo;
	}

	public int getIdCarrello() {
		return this.idCarrello;
	}

	public void setIdCarrello(int idCarrello) {
		this.idCarrello = idCarrello;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ComponeId))
			return false;
		ComponeId castOther = (ComponeId) other;

		return (this.getIdArticolo() == castOther.getIdArticolo())
				&& (this.getIdCarrello() == castOther.getIdCarrello());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdArticolo();
		result = 37 * result + this.getIdCarrello();
		return result;
	}

}
