package it.unirc.pwm.ht;
// Generated 11 dic 2023, 17:22:19 by Hibernate Tools 6.1.3.Final



/**
 * Compone generated by hbm2java
 */
public class Compone  implements java.io.Serializable {


     private ComponeId id;
     private Articolo articolo;
     private Carrello carrello;
     private float prezzoAcquisto;
     private int quantita;

    public Compone() {
    }

    public Compone(ComponeId id, Articolo articolo, Carrello carrello, float prezzoAcquisto, int quantita) {
       this.id = id;
       this.articolo = articolo;
       this.carrello = carrello;
       this.prezzoAcquisto = prezzoAcquisto;
       this.quantita = quantita;
    }
   
    public ComponeId getId() {
        return this.id;
    }
    
    public void setId(ComponeId id) {
        this.id = id;
    }
    public Articolo getArticolo() {
        return this.articolo;
    }
    
    public void setArticolo(Articolo articolo) {
        this.articolo = articolo;
    }
    public Carrello getCarrello() {
        return this.carrello;
    }
    
    public void setCarrello(Carrello carrello) {
        this.carrello = carrello;
    }
    public float getPrezzoAcquisto() {
        return this.prezzoAcquisto;
    }
    
    public void setPrezzoAcquisto(float prezzoAcquisto) {
        this.prezzoAcquisto = prezzoAcquisto;
    }
    public int getQuantita() {
        return this.quantita;
    }
    
    public void setQuantita(int quantita) {
        this.quantita = quantita;
    }




}


