package it.unirc.pwm.ht;
// Generated 11 dic 2023, 17:22:19 by Hibernate Tools 6.1.3.Final


import java.util.HashSet;
import java.util.Set;

/**
 * Indirizzospedizione generated by hbm2java
 */
public class Indirizzospedizione  implements java.io.Serializable {


     private Integer idIndirizzoSpedizione;
     private Cliente cliente;
     private byte preferito;
     private String regione;
     private String provincia;
     private String citta;
     private String via;
     private String ncivico;
     private int cap;
     private long telefono;
     private Set ordines = new HashSet(0);

    public Indirizzospedizione() {
    }

	
    public Indirizzospedizione(Cliente cliente, byte preferito, String regione, String provincia, String citta, String via, String ncivico, int cap, long telefono) {
        this.cliente = cliente;
        this.preferito = preferito;
        this.regione = regione;
        this.provincia = provincia;
        this.citta = citta;
        this.via = via;
        this.ncivico = ncivico;
        this.cap = cap;
        this.telefono = telefono;
    }
    public Indirizzospedizione(Cliente cliente, byte preferito, String regione, String provincia, String citta, String via, String ncivico, int cap, long telefono, Set ordines) {
       this.cliente = cliente;
       this.preferito = preferito;
       this.regione = regione;
       this.provincia = provincia;
       this.citta = citta;
       this.via = via;
       this.ncivico = ncivico;
       this.cap = cap;
       this.telefono = telefono;
       this.ordines = ordines;
    }
   
    public Integer getIdIndirizzoSpedizione() {
        return this.idIndirizzoSpedizione;
    }
    
    public void setIdIndirizzoSpedizione(Integer idIndirizzoSpedizione) {
        this.idIndirizzoSpedizione = idIndirizzoSpedizione;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public byte getPreferito() {
        return this.preferito;
    }
    
    public void setPreferito(byte preferito) {
        this.preferito = preferito;
    }
    public String getRegione() {
        return this.regione;
    }
    
    public void setRegione(String regione) {
        this.regione = regione;
    }
    public String getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(String provincia) {
        this.provincia = provincia;
    }
    public String getCitta() {
        return this.citta;
    }
    
    public void setCitta(String citta) {
        this.citta = citta;
    }
    public String getVia() {
        return this.via;
    }
    
    public void setVia(String via) {
        this.via = via;
    }
    public String getNcivico() {
        return this.ncivico;
    }
    
    public void setNcivico(String ncivico) {
        this.ncivico = ncivico;
    }
    public int getCap() {
        return this.cap;
    }
    
    public void setCap(int cap) {
        this.cap = cap;
    }
    public long getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(long telefono) {
        this.telefono = telefono;
    }
    public Set getOrdines() {
        return this.ordines;
    }
    
    public void setOrdines(Set ordines) {
        this.ordines = ordines;
    }




}


