package it.unirc.pwm.ht;
// Generated 12 dic 2023, 12:22:05 by Hibernate Tools 6.1.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Magazzino generated by hbm2java
 */
public class Magazzino implements java.io.Serializable {

	private Integer codiceMagazzino;
	private String regione;
	private String provincia;
	private String citta;
	private String via;
	private String ncivico;
	private int cap;
	private Set dispones = new HashSet(0);

	public Magazzino() {
	}

	public Magazzino(String regione, String provincia, String citta, String via, String ncivico, int cap) {
		this.regione = regione;
		this.provincia = provincia;
		this.citta = citta;
		this.via = via;
		this.ncivico = ncivico;
		this.cap = cap;
	}

	public Magazzino(String regione, String provincia, String citta, String via, String ncivico, int cap,
			Set dispones) {
		this.regione = regione;
		this.provincia = provincia;
		this.citta = citta;
		this.via = via;
		this.ncivico = ncivico;
		this.cap = cap;
		this.dispones = dispones;
	}

	public Integer getCodiceMagazzino() {
		return this.codiceMagazzino;
	}

	public void setCodiceMagazzino(Integer codiceMagazzino) {
		this.codiceMagazzino = codiceMagazzino;
	}

	public String getRegione() {
		return this.regione;
	}

	public void setRegione(String regione) {
		this.regione = regione;
	}

	public String getProvincia() {
		return this.provincia;
	}

	public void setProvincia(String provincia) {
		this.provincia = provincia;
	}

	public String getCitta() {
		return this.citta;
	}

	public void setCitta(String citta) {
		this.citta = citta;
	}

	public String getVia() {
		return this.via;
	}

	public void setVia(String via) {
		this.via = via;
	}

	public String getNcivico() {
		return this.ncivico;
	}

	public void setNcivico(String ncivico) {
		this.ncivico = ncivico;
	}

	public int getCap() {
		return this.cap;
	}

	public void setCap(int cap) {
		this.cap = cap;
	}

	public Set getDispones() {
		return this.dispones;
	}

	public void setDispones(Set dispones) {
		this.dispones = dispones;
	}

}
