package it.unirc.pwm.ht;
// Generated 7 dic 2023, 12:33:12 by Hibernate Tools 6.1.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Metodospedizione generated by hbm2java
 */
public class Metodospedizione implements java.io.Serializable {

	private Integer idMetodoSpedizione;
	private String tipo;
	private float speseSpedizione;
	private Set ordines = new HashSet(0);

	public Metodospedizione() {
	}

	public Metodospedizione(String tipo, float speseSpedizione) {
		this.tipo = tipo;
		this.speseSpedizione = speseSpedizione;
	}

	public Metodospedizione(String tipo, float speseSpedizione, Set ordines) {
		this.tipo = tipo;
		this.speseSpedizione = speseSpedizione;
		this.ordines = ordines;
	}

	public Integer getIdMetodoSpedizione() {
		return this.idMetodoSpedizione;
	}

	public void setIdMetodoSpedizione(Integer idMetodoSpedizione) {
		this.idMetodoSpedizione = idMetodoSpedizione;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public float getSpeseSpedizione() {
		return this.speseSpedizione;
	}

	public void setSpeseSpedizione(float speseSpedizione) {
		this.speseSpedizione = speseSpedizione;
	}

	public Set getOrdines() {
		return this.ordines;
	}

	public void setOrdines(Set ordines) {
		this.ordines = ordines;
	}

}
