package it.unirc.pwm.ht;
// Generated 7 dic 2023, 14:54:20 by Hibernate Tools 6.1.3.Final


import java.sql.Date;

/**
 * Spedizione generated by hbm2java
 */
public class Spedizione  implements java.io.Serializable {


     private Integer idSpedizione;
     private Ordine ordine;
     private Date dataPartenza;
     private Date dataArrivo;
     private String regione;
     private String provincia;
     private String citta;
     private String via;
     private String ncivico;
     private int cap;

    public Spedizione() {
    }

    public Spedizione(Ordine ordine, Date dataPartenza, Date dataArrivo, String regione, String provincia, String citta, String via, String ncivico, int cap) {
       this.ordine = ordine;
       this.dataPartenza = dataPartenza;
       this.dataArrivo = dataArrivo;
       this.regione = regione;
       this.provincia = provincia;
       this.citta = citta;
       this.via = via;
       this.ncivico = ncivico;
       this.cap = cap;
    }
   
    public Integer getIdSpedizione() {
        return this.idSpedizione;
    }
    
    public void setIdSpedizione(Integer idSpedizione) {
        this.idSpedizione = idSpedizione;
    }
    public Ordine getOrdine() {
        return this.ordine;
    }
    
    public void setOrdine(Ordine ordine) {
        this.ordine = ordine;
    }
    public Date getDataPartenza() {
        return this.dataPartenza;
    }
    
    public void setDataPartenza(Date dataPartenza) {
        this.dataPartenza = dataPartenza;
    }
    public Date getDataArrivo() {
        return this.dataArrivo;
    }
    
    public void setDataArrivo(Date dataArrivo) {
        this.dataArrivo = dataArrivo;
    }
    public String getRegione() {
        return this.regione;
    }
    
    public void setRegione(String regione) {
        this.regione = regione;
    }
    public String getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(String provincia) {
        this.provincia = provincia;
    }
    public String getCitta() {
        return this.citta;
    }
    
    public void setCitta(String citta) {
        this.citta = citta;
    }
    public String getVia() {
        return this.via;
    }
    
    public void setVia(String via) {
        this.via = via;
    }
    public String getNcivico() {
        return this.ncivico;
    }
    
    public void setNcivico(String ncivico) {
        this.ncivico = ncivico;
    }
    public int getCap() {
        return this.cap;
    }
    
    public void setCap(int cap) {
        this.cap = cap;
    }




}


